apiVersion: v1
kind: Service
metadata:
  name: tf-ps-1
spec:
  clusterIP: None
  ports:
    - port: 2222
      targetPort: 2222
  selector:
    app: tf-ps-1
---
apiVersion: v1
kind: Pod
metadata:
  name: tf-ps-1
  labels:
     app: tf-ps-1
spec:
      containers:
        - name: worker
          image: gcr.io/tensorflow/tensorflow
          ports:
           - containerPort: 2222
          volumeMounts:
           - mountPath: /tensorflow
             name: tf-volume
      volumes:
         - name: tf-volume
           hostPath:
              path: /root/tensorflow
